# +-------------------------+
# | Étienne <maiste> Marais |
# |     Zola config file    |
# |         (C) MIT         |
# +-------------------------+

# Intel

theme = "tale-zola"
base_url = "https://maiste.github.io"
title = "Maiste [mɑːïsté]"
description = "Another useless blog you might find useful."
taxonomies = [
  {name = "tags"},
]

# Options

highlight_code = true
generate_feed = true


[extra]

# Author information

author = "Maiste"
github = "https://github.com/maiste/"
email = "etienne[at]maiste.fr"


## Menu {{

[[extra.menu]]
name = "Blog"
url = "/"

[[extra.menu]]
name = "Data"
url = "data"

[[extra.menu]]
name = "About"
url = "about"

[[extra.menu]]
name = "Tags"
url = "tags"

## }}

## Footer {{

[extra.footer]
start_year = "2020"
info = "<a href=\"https://www.getzola.org\">Zola</a> with <a href=\"https://github.com/aaranxu/tale-zola\">Tala-Zola</a> theme."

# }}

# Customise names

[extra.expressions]

top = "Up"
written_by = "By"
